from os import PathLike
from dataclasses import dataclass, field
from typing import (cast,
                    List,
                    Union,
                    Type,
                    TypeVar,
                    Optional,
)

from omegaconf import OmegaConf as om
from omegaconf.errors import OmegaConfBaseException

C = TypeVar("C", bound="BaseConfig")

class BaseConfig:
    @classmethod
    def load(
        cls: Type[C],
        path: Union[str, PathLike],
        ) -> C:
        """Load from YAML file"""
        schema = om.structured(cls)
        try:
            raw = om.load(str(path))
            conf = om.merge(schema, raw)
            return cast(C, om.to_object(conf))
        except OmegaConfBaseException as e:
            raise ValueError(str(e))

@dataclass
class ModelConfig(BaseConfig):
    name: str = "MLP"
    """
    What base network architecture to use.
    """

    dropout: float = 0
    """
    Dropout rate.
    """

    alignment_layers: Optional[dict] = None
    """
    A dictionary specifying the layers participating in alignment computation and their corresponding input layers
    none indicates all layers to praticipate. Both key and values should be layer names from model.named_modules() 
    """

@dataclass
class DatasetConfig(BaseConfig):
    name: str = "MNIST"
    """
    What dataset to use.
    """

    path: Optional[str] = None
    """
    Relative path containing datasets.
    """

    download: bool = False
    """
    Download the dataset if it does not exist.
    """

@dataclass
class OptimizerConfig(BaseConfig):
    name: str = "Adam"
    """
    What optimizer to train with.
    """

    lr: float = 1e-3
    """
    Learning rate.
    """

    weight_decay: float = 0
    """
    Weight decay.
    """

@dataclass
class TrainingConfig(BaseConfig):
    batch_size: int = 1024
    """
    What batch size to pass to DataLoader.
    """

    epochs: int = 100
    """
    How many epochs to train the networks on.
    """

    replicates: int = 5
    """
    How many replicates of each network to train.
    """

@dataclass
class AlignmentConfig(BaseConfig):
    no_alignment: bool = False
    """
    If used, will not measure alignment during training and testing.
    """

    delta_weights: bool = False
    """
    If used, will measure delta-weights during training.
    """

    frequency: int = 1
    """
    How frequently to measure alignment etc. (how many minibatches).
    """

@dataclass
class CheckpointingConfig(BaseConfig):
    use_prev: bool = False
    """
    If used, will pick up training off previous checkpoint.
    """

    save_checkpoints: bool = False
    """
    If used, will save checkpoints of models.
    """

    frequency: int = 1
    """
    Frequency (by epoch) to save checkpoints of models.
    """

    use_wandb: bool = False
    """
    If used, will log experiment to WandB.
    """

@dataclass
class ExtraConfig(BaseConfig):
    num_drops: int = 9
    """
    Number of dropout fractions for progressive dropout.
    """

    dropout_by_layer: bool = False
    """
    Whether to do progressive dropout by layer or across all layers.
    """
    
    #############################  For alignment_comparison and loading_prediction experiments
    comparison: str = "lr"
    """
    Determines what should be compared, e.g, 'lr', 'regularizer'. 
    """

    regularizers: List[str] = field(default_factory=lambda: ["none", "dropout", "weight_decay"])
    """
    What regularizers to use for comparison
    """

    lrs: List[float] = field(default_factory=lambda: [1e-2, 1e-3, 1e-4])
    """
    What learning rates to use for comparison
    """

    compare_dropout: float = 0.5
    """
    Dropout when doing regularizer comparison.
    """
    
    compare_wd: float = 1e-5
    """
    Weight-decay when doing regularizer comparison.
    """

    #############################  For adversarial_shaping experiment
    cutoffs: List[float] = field(default_factory=lambda: [1e-2, 1e-3, 1e-4, 0.0])
    """
    What fraction of total variance to cut eigenvalues off at.
    """

    manual_frequency: int = 5
    """
    How frequently (by epoch) to do manual shaping with eigenvectors.
    """

@dataclass
class ExperimentConfig(BaseConfig):
   """
   Alignment Experiment Configuration.
   """
   
   experiment: Optional[str] = None
   """
   The name of the run.
   """

   results_path: Optional[str] = None
   """
   Relative path to results generated by this package.
   """

   no_save: bool = False
   """
   Prevents saving of results or plots.
   """
   
   just_plot: bool = False
   """
   Plot saved data without retraining and analyzing networks.
   """
   
   save_networks: bool = False
   """
   If no_save wasn't provided, will also save networks that are trained.
   """
   
   show_params: bool = False
   """
   Show parameters of previously saved experiment without doing anything else.
   """
   
   show_all: bool = False
   """
   If true, will show all plots at once rather than having the user close each one for the next.
   """
   
   device: Optional[str] = None
   """
   Which device to use (automatic if not provided).
   """

   use_timestamp: bool = False
   """
   If used, will save data in a folder named after the current time (or whatever is provided in timestamp).
   """

   timestamp: Optional[str] = None
   """
   The timestamp of a previous experiment to plot or observe parameters.
   """

   dataset: DatasetConfig = field(default_factory=DatasetConfig)
   """
   Arguments for datasets configs.
   """

   model: ModelConfig = field(default_factory=ModelConfig)
   """
   Arguments for model configs.
   """

   optimizer: OptimizerConfig = field(default_factory=OptimizerConfig)
   """
   Arguments for optimizer parameters.
   """
   
   training: TrainingConfig = field(default_factory=TrainingConfig)
   """
   Arguments for defining the network type, dataset, optimizer, and other metaparameters.
   """

   alignment: AlignmentConfig = field(default_factory=AlignmentConfig)
   """
   Arguments for alignment analysis parameters.
   """

   checkpointing: CheckpointingConfig = field(default_factory=CheckpointingConfig)
   """
   Arguments for managing checkpointing when training networks.
   """

   extra: ExtraConfig = field(default_factory=ExtraConfig)
   """
   Add arguments for determining how to run progressive dropout experiments.
   """