experiment: alignment_stats
results_path: # path to save/load results
no_save: False
just_plot: False
save_networks: False
show_params: False
show_all: False
use_timestamp: False

dataset:
  name: MNIST
  path:
  download: True

model:
  name: MLP
  dropout: 0
  alignment_layers: null

optimizer:
  name: Adam
  lr: 1e-3
  weight_decay: 0

training:
  batch_size: 1024
  epochs: 1
  replicates: 1

alignment:
  no_alignment: False
  delta_weights: False
  frequency: 1

checkpointing:
  use_prev: False
  save_checkpoints: False
  frequency: 1
  use_wandb: False

extra:
  num_drops: 9
  dropout_by_layer: False

  comparison: "lr"
  regularizers: ["none", "dropout", "weight_decay"]
  lrs: [1e-2, 1e-3, 1e-4]
  compare_dropout: 0.5
  compare_wd: 1e-5
  cutoffs: [1e-2, 1e-3, 1e-4, 0.0]
  manual_frequency: 5