experiment: imagenet_alignment_pretrained
results_path: "/path/to/results/imagenet_pretrained"
no_save: false
just_plot: false
save_networks: false
show_params: false
show_all: false
use_timestamp: false

dataset:
  name: ImageNet
  path: "/path/to/imagenet"
  download: false

model:
  name: alexnet
  dropout: 0
  alignment_layers: null

optimizer:
  name: Adam
  lr: 1e-3
  weight_decay: 0

training:
  batch_size: 256
  epochs: 0  # zero epochs; we use the pretrained weights
  replicates: 1

alignment:
  no_alignment: false
  delta_weights: false
  frequency: 1

checkpointing:
  use_prev: false
  save_checkpoints: false
  frequency: 1
  use_wandb: false

extra:
  num_drops: 9
  dropout_by_layer: false