experiment: "alignment_experiment"
results_path: "results/pruning_test"
no_save: false
just_plot: false
save_networks: true
show_params: false
show_all: false
device: "cuda"
use_timestamp: true
timestamp: null
ddp_world_size: 1

dataset:
  dataset_name: "MNIST"
  dataset_path: "/n/holylabs/LABS/kempner_dev/Users/hsafaai/Code/alignment/data"

model:
  model_name: "mlp"
  dropout: 0.0
  alignment_layers: null

training:
  do_train: true
  epochs: 5
  batch_size: 1024
  replicates: 1
  name: "Adam"
  lr: 1e-3
  weight_decay: 0.0

alignment:
  do_alignment: true
  metric: "RQ"
  methods: ["RQ"]
  measure_expected: false
  frequency: 1
  bins: 50
  cnn_mode: "unfold"
  scale_by_norm: false
  run_progressive: true
  run_eigenvector: true
  dropout_min: 0.0
  dropout_max: 0.9
  dropout_steps: 10

checkpointing:
  use_prev: false
  save_checkpoints: true
  frequency: 1
  use_wandb: false

plots:
  show_loss: true
  show_dropout: true
  show_eigenfeatures: true
  show_eig_dropout: true

extra:
  num_drops: 10
  progressive_dropout_on_train: false
  single_layer_mode: false
  aggregate_alignment: false
  dropout_pruning_mode: "per_layer_combined"
  dropout_mode: "scaled"
  exclude_classification_layer: true 