experiment: "mnist_alignment_example"
results_path:   # <-- Add path to where results to be saved/loaded
no_save: false   ## if true, skip saving results and plots
just_plot: false ## If true, skip the experiment’s main() logic, only load previously saved results and call plot_from_existing()
save_networks: false ## If true, also save trained networks (self.save_networks(...)) after training.
show_params: false  ## keep the plots open WE CAN REMOVE THIS
show_all: false     ## ## keep the plots open WE CAN REMOVE THIS
use_timestamp: false ## If use_timestamp is true, the code stores results in subfolders named by timestamp (an ISO/time string).
timestamp: null

ddp_world_size: 2

dataset:
  name: "ImageNet" # "MNIST", "CIFAR10", "CIFAR100", "ImageNet", etc.
  path:   # <-- Add path to your dataset ## path to dataset

model:
  name: "AlexNet" ## base artitecture, e.g., "MLP", "CNN2P2", "AlexNet".
  dropout: 0 ## Dropout fraction 0 to 1
  alignment_layers: null
   # "layer2.0": "layer1.0"
   # a dict of layer names: source_layer. if null it will be set to all layers. 
    #"features.8": null    # the null after "features.8" refers to the fact that we don't mention a particular input for this layer and use what it gets

training:
  do_train: true  
  epochs: 10
  batch_size: 100
  lr:  1e-3
  replicates: 2
  name:  "Adam"
  weight_decay:  0.0

alignment:
#  do_train_alignment: false
#  do_test_alignment: true
  do_alignment:  false     
  methods: ["RQ"]  
  measure_expected: False
  frequency: 1
  bins:  50
  cnn_mode: "unfold" #"unfold: Single covariance across all patches", "patch: Patchwise alignment, weighting by variance", "old""

checkpointing:
  use_wandb: true
  use_prev: false
  save_checkpoints: false
  frequency: 1

plots:
  show_loss: true
  show_dropout: true
  show_eigenfeatures: true
  show_eig_dropout: true

extra:
  num_drops: 50
  dropout_by_layer: false
  single_layer_mode: false # dropout_by_layer must be true to work
  progressive_dropout_on_train: false
  aggregate_alignment: true

#  	•	If aggregate_alignment=True, we directly append the alignment each batch to results["alignment"].
#  	•	If aggregate_alignment=False, we temporarily store in epoch_align_data and only append once at the end of the epoch.

  #comparison: "lr" ## for “alignment_comparison” style experiments
  #regularizers: ["none", "dropout", "weight_decay"]
  #lrs: [1e-3, 1e-4]
  #compare_dropout: 0.5
  #compare_wd: 1e-5
  #cutoffs: [1e-2, 1e-3, 1e-4, 0.0]
  #manual_frequency: 5

  # python src/alignment_v2/experiments/alignment_experiments.py --config .vscode/config_alignment_stats_v2.yaml