experiment: "mnist_alignment_example"
results_path:   ## path to where results to be saved/loaded
no_save: false   ## if true, skip saving results and plots
just_plot: false ## If true, skip the experiment’s main() logic, only load previously saved results and call plot_from_existing()
save_networks: false ## If true, also save trained networks (self.save_networks(...)) after training.
show_params: false  ## keep the plots open WE CAN REMOVE THIS
show_all: false     ## ## keep the plots open WE CAN REMOVE THIS
use_timestamp: false ## If use_timestamp is true, the code stores results in subfolders named by timestamp (an ISO/time string).
timestamp: null

dataset:
  name: "MNIST" # "MNIST", "CIFAR10", "CIFAR100", "ImageNet", etc.
  path: ## path to dataset

model:
  name: "MLP" ## base artitecture, e.g., "MLP", "CNN2P2", etc.
  dropout: 0 ## Dropout fraction 0 to 1
  alignment_layers: null # a dict of layer names: source_layer. if null it will be set to all layers. 
    #"features.8": null    # the null after "features.8" refers to the fact that we don't mention a particular input for this layer and use what it gets


optimizer:
  name: "Adam"
  lr: 1e-4
  weight_decay: 0

training:
  do_train: false  # <--- unified training toggle
  batch_size: 64
  epochs: 10
  replicates: 1 # number of nets to train

alignment:
  methods: ["RQ", "MI_0", "MI_1"]  # <--- a list of desired alignment metrics
  compute_during_training: false
  compute_during_inference: true
  frequency: 1  # how often to compute alignment (mini-batch frequency)
  # optional advanced flags:
  measure_weight_deltas: false

checkpointing:
  use_wandb: true
  use_prev: false
  save_checkpoints: false
  frequency: 1

plots:
  # <--- new section that decides which plots to generate
  show_loss: true
  show_dropout: true
  show_eigenfeatures: true
  show_eig_dropout: true

extra:
  num_drops: 10
  dropout_by_layer: false
  #comparison: "lr" ## for “alignment_comparison” style experiments
  #regularizers: ["none", "dropout", "weight_decay"]
  #lrs: [1e-3, 1e-4]
  #compare_dropout: 0.5
  #compare_wd: 1e-5
  #cutoffs: [1e-2, 1e-3, 1e-4, 0.0]
  #manual_frequency: 5