experiment: alignment_stats
results_path: # <-- Add path to where results to be saved/loaded
no_save: False
just_plot: False
save_networks: False
show_params: False
show_all: False
#device: cpu 
use_timestamp: False
#timestamp: # The timestamp of previous experiment to plot.

dataset:
  name: MNIST
  path: # <-- Add path to your dataset
  download: True # Downloads it if it does not exist. 

model:
  name: MLP
  default_dropout: 0

optimizer:
  name: Adam
  default_lr: 1e-3
  default_wd: 0

training:
  batch_size: 1024
  epochs: 1
  replicates: 1

alignment:
  no_alignment: False
  ignore_flag: False
  delta_weights: False
  frequency: 1

checkpointing:
  use_prev: False
  save_checkpoints: False
  frequency: 1
  use_wandb: False

extra:
  num_drops: 9
  dropout_by_layer: False