#!/usr/bin/env python3
"""
Collect SCAR paper artifacts (tables + key figures) from experiment job directories.

This script is meant to be run AFTER the SLURM batch suite finishes.

What it does:
- Finds the latest job directory for each expected experiment name under --results-base
- Loads the corresponding results_*.json
- Generates LaTeX table snippets into drafts/LLM_prune/paper_artifacts/tables/
- Copies a small set of "paper figure" images into drafts/LLM_prune/ as the placeholder_*.png files
  used by `drafts/LLM_prune/scar_paper_icml_v5.tex` (so the paper auto-fills without manual edits).

Example:
  python scripts/collect_paper_artifacts.py \
    --results-base /n/holylfs06/LABS/kempner_project_b/Lab/alignment/Prune_LLM \
    --draft-dir /n/holylabs/kempner_dev/Users/hsafaai/Code/alignment/drafts/LLM_prune
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


# -----------------------------
# Helpers
# -----------------------------


def _latest_results_json(job_dir: Path) -> Optional[Path]:
    candidates: List[Path] = []
    if (job_dir / "results").exists():
        candidates.extend(sorted((job_dir / "results").glob("results_*.json")))
    candidates.extend(sorted(job_dir.glob("results_*.json")))
    if not candidates:
        return None
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0]


def find_latest_job_dir(results_base: Path, experiment_name: str) -> Optional[Path]:
    """
    Job directories are created as:
      {experiment_name}_{timestamp}_{job_id}/
    """
    if not results_base.exists():
        return None
    candidates = [p for p in results_base.iterdir() if p.is_dir() and p.name.startswith(f"{experiment_name}_")]
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    for job_dir in candidates:
        if _latest_results_json(job_dir) is not None:
            return job_dir
    return None


def load_results(job_dir: Path) -> Dict[str, Any]:
    path = _latest_results_json(job_dir)
    if path is None:
        raise FileNotFoundError(f"No results_*.json found in {job_dir} or {job_dir/'results'}")
    return json.loads(path.read_text())


def _get_pruned_entry(
    pruning_results: Dict[str, Any],
    metric: str,
    mode: str,
    sparsity: float,
) -> Optional[Dict[str, Any]]:
    for v in pruning_results.values():
        if not isinstance(v, dict):
            continue
        if v.get("metric") == metric and v.get("mode") == mode and float(v.get("sparsity", -1)) == float(sparsity):
            return v
    return None


def _pick_mode(
    pruning_results: Dict[str, Any],
    metric: str,
    sparsity: float,
    mode: str,
) -> Tuple[str, Optional[Dict[str, Any]]]:
    """
    mode:
      - "low" or "high": choose that mode
      - "best": choose the better of low/high by perplexity
    """
    if mode in {"low", "high"}:
        return mode, _get_pruned_entry(pruning_results, metric=metric, mode=mode, sparsity=sparsity)

    low = _get_pruned_entry(pruning_results, metric=metric, mode="low", sparsity=sparsity)
    high = _get_pruned_entry(pruning_results, metric=metric, mode="high", sparsity=sparsity)

    def ppl(x: Optional[Dict[str, Any]]) -> float:
        if not x:
            return float("inf")
        v = x.get("perplexity")
        return float(v) if v is not None else float("inf")

    if ppl(low) <= ppl(high):
        return "low", low
    return "high", high


def _fmt(x: Any, digits: int = 1) -> str:
    if x is None:
        return "--"
    try:
        xf = float(x)
    except Exception:
        return "--"
    if xf != xf:  # NaN
        return "--"
    return f"{xf:.{digits}f}"


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def latex_tabular(rows: List[List[str]], align_spec: str) -> str:
    lines = []
    lines.append("% Auto-generated by scripts/collect_paper_artifacts.py")
    lines.append(f"\\begin{{tabular}}{{{align_spec}}}")
    lines.append("\\toprule")
    for i, r in enumerate(rows):
        lines.append(" & ".join(r) + " \\\\")
        if i == 0:
            lines.append("\\midrule")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("")
    return "\n".join(lines)


def safe_copy(src: Path, dst: Path) -> bool:
    if not src.exists():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return True


# -----------------------------
# Table generators
# -----------------------------


def make_table_main_50(
    llama3_main: Dict[str, Any],
    llama3_noprotect: Optional[Dict[str, Any]],
    llama3_protect_baselines: Optional[Dict[str, Any]],
    out_path: Path,
    sparsity: float = 0.5,
    mode: str = "best",
) -> None:
    pruning_main = llama3_main.get("pruning_results") or {}
    evaluation_main = llama3_main.get("evaluation") or {}

    # Columns used in the draft Table 1
    cols: List[Tuple[str, str, int]] = [
        ("PPL$\\downarrow$", "perplexity", 1),
        ("MMLU", "accuracy_mmlu", 1),
        ("Hella", "accuracy_hellaswag", 1),
        ("PIQA", "accuracy_piqa", 1),
        ("BoolQ", "accuracy_boolq", 1),
    ]

    rows: List[List[str]] = []
    rows.append(["Method"] + [h for h, _, _ in cols])

    # Unpruned row
    baseline_ppl = evaluation_main.get("baseline_perplexity")
    baseline_metrics = evaluation_main.get("baseline_metrics") or {}
    unpruned_vals = {"perplexity": baseline_ppl, **(baseline_metrics if isinstance(baseline_metrics, dict) else {})}
    rows.append(["Unpruned"] + [_fmt(unpruned_vals.get(k), d) for _, k, d in cols])

    # Main rows from the "main" run
    methods_main: List[Tuple[str, str]] = [
        ("Magnitude (channel)", "weight_magnitude"),
        ("Wanda (channel)", "wanda"),
        ("SparseGPT (channel)", "sparsegpt"),
        ("Act. L2", "activation_l2_norm"),
        ("RQ", "rayleigh_quotient"),
        ("SCAR-LP", "scar_loss_proxy"),
        ("SCAR-Prot", "supernode_protection_score"),
        ("SCAR-Conn", "supernode_connectivity_score"),
    ]

    for label, metric in methods_main:
        picked_mode, entry = _pick_mode(pruning_main, metric=metric, sparsity=sparsity, mode=mode)
        if entry is None:
            rows.append([label] + ["--"] * len(cols))
            continue
        rows.append([label] + [_fmt(entry.get(k), d) for _, k, d in cols])

    # Optional extra rows (if those experiments are present)
    if llama3_noprotect is not None:
        pr = llama3_noprotect.get("pruning_results") or {}
        picked_mode, entry = _pick_mode(pr, metric="scar_loss_proxy", sparsity=sparsity, mode="low")
        if entry is not None:
            rows.append(["LP-no-protect"] + [_fmt(entry.get(k), d) for _, k, d in cols])

    if llama3_protect_baselines is not None:
        pr = llama3_protect_baselines.get("pruning_results") or {}
        for label, metric in [("Protect+Magnitude", "weight_magnitude"), ("Protect+Wanda", "wanda")]:
            picked_mode, entry = _pick_mode(pr, metric=metric, sparsity=sparsity, mode="low")
            if entry is not None:
                rows.append([label] + [_fmt(entry.get(k), d) for _, k, d in cols])

    content = latex_tabular(rows, align_spec="@{}l" + "c" * len(cols) + "@{}")
    write_text(out_path, content)


def make_table_sparsity_tradeoff(
    llama3_main: Dict[str, Any],
    out_path: Path,
    sparsities: List[float],
    mode: str = "low",
) -> None:
    pruning = llama3_main.get("pruning_results") or {}
    baseline_ppl = (llama3_main.get("evaluation") or {}).get("baseline_perplexity")

    methods: List[Tuple[str, str]] = [
        ("Wanda (channel)", "wanda"),
        ("SparseGPT (channel)", "sparsegpt"),
        ("SCAR-LP", "scar_loss_proxy"),
        ("SCAR-Prot", "supernode_protection_score"),
        ("SCAR-Conn", "supernode_connectivity_score"),
    ]

    header = ["Method"] + [f"{int(100*s)}\\%" for s in sparsities]
    rows: List[List[str]] = [header]
    if baseline_ppl is not None:
        rows.append(["Baseline"] + [_fmt(baseline_ppl, 1)] * len(sparsities))

    for label, metric in methods:
        row = [label]
        for s in sparsities:
            picked_mode, entry = _pick_mode(pruning, metric=metric, sparsity=s, mode=mode)
            row.append(_fmt(entry.get("perplexity") if entry else None, 1))
        rows.append(row)

    content = latex_tabular(rows, align_spec="@{}l" + "c" * len(sparsities) + "@{}")
    write_text(out_path, content)


def make_table_generalization(
    model_results: List[Tuple[str, Dict[str, Any]]],
    out_path: Path,
    sparsity: float = 0.5,
    mode: str = "best",
) -> None:
    rows: List[List[str]] = []
    rows.append(["Model", "Method", "PPL$\\downarrow$", "MMLU", "Avg.$\\uparrow$"])

    for model_label, res in model_results:
        pr = res.get("pruning_results") or {}
        # Wanda baseline
        _, wanda = _pick_mode(pr, metric="wanda", sparsity=sparsity, mode=mode)
        _, scar = _pick_mode(pr, metric="supernode_connectivity_score", sparsity=sparsity, mode=mode)

        def avg_acc(entry: Optional[Dict[str, Any]]) -> Optional[float]:
            if not entry:
                return None
            accs = [float(v) for k, v in entry.items() if isinstance(k, str) and k.startswith("accuracy_") and v is not None]
            return sum(accs) / len(accs) if accs else None

        for method_label, entry in [("Wanda (channel)", wanda), ("SCAR-Conn", scar)]:
            rows.append(
                [
                    model_label,
                    method_label,
                    _fmt(entry.get("perplexity") if entry else None, 1),
                    _fmt(entry.get("accuracy_mmlu") if entry else None, 1),
                    _fmt(avg_acc(entry), 1),
                ]
            )

    content = latex_tabular(rows, align_spec="@{}llccc@{}")
    write_text(out_path, content)


def make_table_halo_redundancy(
    llama3_main: Dict[str, Any],
    out_path: Path,
) -> None:
    halo = llama3_main.get("halo_analysis") or {}
    agg = halo.get("aggregate") or {}

    # The current analysis uses |corr|; we expose it directly for the draft table.
    rows: List[List[str]] = []
    rows.append(["Group Pair", "Mean", "Std"])

    def get(group: str, key: str) -> Any:
        return (agg.get(group) or {}).get(key)

    rows.append(["Within-Halo", _fmt(get("halo_halo", "mean"), 3), _fmt(get("halo_halo", "std"), 3)])
    rows.append(["Within-Non-Halo", _fmt(get("non_halo", "mean"), 3), _fmt(get("non_halo", "std"), 3)])
    rows.append(["Cross (Halo $\\leftrightarrow$ Non-Halo)", _fmt(get("cross", "mean"), 3), _fmt(get("cross", "std"), 3)])

    content = latex_tabular(rows, align_spec="@{}lcc@{}")
    write_text(out_path, content)


def make_table_full_benchmarks_50(
    llama3_main: Dict[str, Any],
    out_path: Path,
    sparsity: float = 0.5,
    mode: str = "best",
) -> None:
    """
    Appendix table: a wider benchmark set at a single sparsity.
    """
    pruning = llama3_main.get("pruning_results") or {}
    evaluation = llama3_main.get("evaluation") or {}

    cols: List[Tuple[str, str, int]] = [
        ("PPL$\\downarrow$", "perplexity", 1),
        ("MMLU", "accuracy_mmlu", 1),
        ("Hella", "accuracy_hellaswag", 1),
        ("PIQA", "accuracy_piqa", 1),
        ("BoolQ", "accuracy_boolq", 1),
        ("WinoG", "accuracy_winogrande", 1),
        ("ARC-E", "accuracy_arc_easy", 1),
        ("ARC-C", "accuracy_arc_challenge", 1),
        ("OBQA", "accuracy_openbookqa", 1),
    ]

    rows: List[List[str]] = []
    rows.append(["Method"] + [h for h, _, _ in cols])

    baseline_ppl = evaluation.get("baseline_perplexity")
    baseline_metrics = evaluation.get("baseline_metrics") or {}
    unpruned_vals = {"perplexity": baseline_ppl, **(baseline_metrics if isinstance(baseline_metrics, dict) else {})}
    rows.append(["Unpruned"] + [_fmt(unpruned_vals.get(k), d) for _, k, d in cols])

    methods: List[Tuple[str, str]] = [
        ("Random", "random"),
        ("Magnitude (channel)", "weight_magnitude"),
        ("Wanda (channel)", "wanda"),
        ("SparseGPT (channel)", "sparsegpt"),
        ("Act. L2", "activation_l2_norm"),
        ("RQ", "rayleigh_quotient"),
        ("Gaussian MI (analytic)", "gaussian_mi_analytic"),
        ("SCAR-LP", "scar_loss_proxy"),
        ("SCAR-Prot", "supernode_protection_score"),
        ("SCAR-Conn", "supernode_connectivity_score"),
    ]

    for label, metric in methods:
        picked_mode, entry = _pick_mode(pruning, metric=metric, sparsity=sparsity, mode=mode if metric != "random" else "low")
        if entry is None:
            rows.append([label] + ["--"] * len(cols))
            continue
        rows.append([label] + [_fmt(entry.get(k), d) for _, k, d in cols])

    content = latex_tabular(rows, align_spec="@{}l" + "c" * len(cols) + "@{}")
    write_text(out_path, content)


def make_table_supernode_control(
    llama3_main: Dict[str, Any],
    llama3_noprotect: Optional[Dict[str, Any]],
    out_path: Path,
    sparsity: float = 0.5,
) -> None:
    rows: List[List[str]] = []
    rows.append(["Strategy", "PPL", "Relative"])

    pr_main = llama3_main.get("pruning_results") or {}
    _, scar = _pick_mode(pr_main, metric="supernode_connectivity_score", sparsity=sparsity, mode="low")
    _, wanda = _pick_mode(pr_main, metric="wanda", sparsity=sparsity, mode="low")

    remove_core_early_ppl = None
    if llama3_noprotect is not None:
        pr = llama3_noprotect.get("pruning_results") or {}
        high = _get_pruned_entry(pr, metric="scar_loss_proxy", mode="high", sparsity=sparsity)
        if high is not None:
            remove_core_early_ppl = high.get("perplexity")

    rows.append(["Remove supernodes early", _fmt(remove_core_early_ppl, 1), "$\\gg$ worse"])
    rows.append(["Wanda (channel)", _fmt(wanda.get("perplexity") if wanda else None, 1), "worse"])
    rows.append(["SCAR-Conn (protect supernodes)", _fmt(scar.get("perplexity") if scar else None, 1), "best"])

    content = latex_tabular(rows, align_spec="@{}lcc@{}")
    write_text(out_path, content)


def make_table_calibration_sensitivity(
    results_base: Path,
    prefix: str,
    out_path: Path,
    sparsity: float = 0.5,
) -> None:
    """
    Collect all runs whose experiment name starts with `prefix` and build a calibration sensitivity table.
    Intended to work with the job-array naming convention from:
      slurm_jobs/prune_llm/paper/run_llama3_8b_calibration_array.sh
    """
    if not results_base.exists():
        return

    job_dirs = [p for p in results_base.iterdir() if p.is_dir() and p.name.startswith(f"{prefix}_")]
    if not job_dirs:
        return

    # Keep the most recent run per (dataset_name, n_samples)
    best: Dict[Tuple[str, int], Tuple[float, Dict[str, Any]]] = {}

    for job_dir in sorted(job_dirs, key=lambda p: p.stat().st_mtime, reverse=True):
        try:
            res = load_results(job_dir)
        except Exception:
            continue

        cfg = res.get("config") or {}
        dataset_name = str(cfg.get("dataset_name", "unknown"))
        n = cfg.get("alignment_data_num_samples")
        try:
            n_int = int(n)
        except Exception:
            continue

        pr = res.get("pruning_results") or {}
        entry = _get_pruned_entry(pr, metric="supernode_connectivity_score", mode="low", sparsity=sparsity)
        ppl = None if entry is None else entry.get("perplexity")
        try:
            ppl_f = float(ppl) if ppl is not None else float("inf")
        except Exception:
            ppl_f = float("inf")

        key = (dataset_name, n_int)
        if key not in best:
            best[key] = (job_dir.stat().st_mtime, {"dataset": dataset_name, "n": n_int, "ppl": ppl_f})

    if not best:
        return

    pretty_name = {
        "wikitext": "WikiText-2",
        "c4": "C4",
        "mixed_wikitext_c4": "Mixed (Wiki + C4)",
        "mixed_wiki_c4": "Mixed (Wiki + C4)",
        "mixed": "Mixed (Wiki + C4)",
    }

    rows: List[List[str]] = []
    rows.append(["Dataset", "\\# seqs", "PPL"])

    # Sort rows for readability: wikitext first, then c4, then others; within by n desc.
    def sort_key(item: Tuple[Tuple[str, int], Tuple[float, Dict[str, Any]]]) -> Tuple[int, str, int]:
        (ds, n), _ = item
        group = 0 if ds == "wikitext" else 1 if ds == "c4" else 2
        return (group, ds, -n)

    for (_, _), (_, rec) in sorted(best.items(), key=sort_key):
        ds = str(rec["dataset"])
        rows.append([pretty_name.get(ds, ds), str(rec["n"]), _fmt(rec["ppl"], 1)])

    content = latex_tabular(rows, align_spec="@{}llc@{}")
    write_text(out_path, content)


# -----------------------------
# Main
# -----------------------------


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results-base", required=True, type=str, help="Base directory containing job dirs (OUTPUT_BASE)")
    ap.add_argument(
        "--draft-dir",
        required=True,
        type=str,
        help="Path to drafts/LLM_prune (where placeholder_*.png live)",
    )
    ap.add_argument(
        "--artifacts-dir",
        type=str,
        default=None,
        help="Where to write paper_artifacts/ (default: {draft-dir}/paper_artifacts)",
    )
    ap.add_argument("--sparsity", type=float, default=0.5, help="Primary sparsity level for tables (default: 0.5)")
    ap.add_argument("--mode", type=str, default="best", choices=["low", "high", "best"], help="Mode selection for tables")

    # Canonical experiment names (these are the ExperimentConfig.name values)
    ap.add_argument("--llama3-main-name", type=str, default="llama3_8b_paper_results")
    ap.add_argument("--mistral-main-name", type=str, default="mistral_7b_paper_results")
    ap.add_argument("--llama2-main-name", type=str, default="llama2_7b_paper_results")
    ap.add_argument("--qwen2-main-name", type=str, default="qwen2_7b_paper_results")
    ap.add_argument("--llama3-noprotect-name", type=str, default="llama3_8b_paper_results_noprotect")
    ap.add_argument("--llama3-protect-baselines-name", type=str, default="llama3_8b_paper_results_protect_baselines")
    ap.add_argument("--llama3-calib-prefix", type=str, default="llama3_8b_paper_results_calib")

    args = ap.parse_args()

    results_base = Path(args.results_base)
    draft_dir = Path(args.draft_dir)
    artifacts_dir = Path(args.artifacts_dir) if args.artifacts_dir else (draft_dir / "paper_artifacts")
    tables_dir = artifacts_dir / "tables"

    # Locate + load main runs
    llama3_main_dir = find_latest_job_dir(results_base, args.llama3_main_name)
    if llama3_main_dir is None:
        raise FileNotFoundError(f"Could not find a run for '{args.llama3_main_name}' under {results_base}")
    llama3_main = load_results(llama3_main_dir)

    mistral_dir = find_latest_job_dir(results_base, args.mistral_main_name)
    llama2_dir = find_latest_job_dir(results_base, args.llama2_main_name)
    qwen2_dir = find_latest_job_dir(results_base, args.qwen2_main_name)

    mistral = load_results(mistral_dir) if mistral_dir else None
    llama2 = load_results(llama2_dir) if llama2_dir else None
    qwen2 = load_results(qwen2_dir) if qwen2_dir else None

    # Optional control runs
    llama3_noprotect_dir = find_latest_job_dir(results_base, args.llama3_noprotect_name)
    llama3_protect_baselines_dir = find_latest_job_dir(results_base, args.llama3_protect_baselines_name)
    llama3_noprotect = load_results(llama3_noprotect_dir) if llama3_noprotect_dir else None
    llama3_protect_baselines = load_results(llama3_protect_baselines_dir) if llama3_protect_baselines_dir else None

    # Generate tables
    make_table_main_50(
        llama3_main=llama3_main,
        llama3_noprotect=llama3_noprotect,
        llama3_protect_baselines=llama3_protect_baselines,
        out_path=tables_dir / "table_main_50.tex",
        sparsity=float(args.sparsity),
        mode=args.mode,
    )
    make_table_sparsity_tradeoff(
        llama3_main=llama3_main,
        out_path=tables_dir / "table_sparsity_ppl.tex",
        sparsities=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
        mode="low",
    )
    make_table_supernode_control(
        llama3_main=llama3_main,
        llama3_noprotect=llama3_noprotect,
        out_path=tables_dir / "table_supernode_control.tex",
        sparsity=float(args.sparsity),
    )
    make_table_halo_redundancy(
        llama3_main=llama3_main,
        out_path=tables_dir / "table_halo_redundancy.tex",
    )
    make_table_full_benchmarks_50(
        llama3_main=llama3_main,
        out_path=tables_dir / "table_full_benchmarks_50.tex",
        sparsity=float(args.sparsity),
        mode=args.mode,
    )
    make_table_calibration_sensitivity(
        results_base=results_base,
        prefix=args.llama3_calib_prefix,
        out_path=tables_dir / "table_calibration_sensitivity.tex",
        sparsity=float(args.sparsity),
    )

    model_rows: List[Tuple[str, Dict[str, Any]]] = []
    if mistral is not None:
        model_rows.append(("Mistral-7B", mistral))
    if llama2 is not None:
        model_rows.append(("Llama-2-7B", llama2))
    if qwen2 is not None:
        model_rows.append(("Qwen2-7B", qwen2))
    if model_rows:
        make_table_generalization(model_rows, out_path=tables_dir / "table_generalization_50.tex", sparsity=float(args.sparsity))

    # Copy key figures into the draft placeholders (no LaTeX edits needed)
    figs = Path(llama3_main_dir) / "figures"
    mapping = [
        (figs / "pruning" / "pruning_comparison.png", draft_dir / "placeholder_sparsity_curves.png"),
        (figs / "histograms" / "histogram_scar_loss_proxy.png", draft_dir / "placeholder_supernode_distribution.png"),
        (figs / "supernode_summary" / "halo_nonhalo_metrics_by_layer.png", draft_dir / "placeholder_halo_redundancy.png"),
        (figs / "supernode_summary" / "supernode_outlier_zscores.png", draft_dir / "placeholder_supernode_analysis.png"),
    ]

    copied = 0
    for src, dst in mapping:
        if safe_copy(src, dst):
            copied += 1

    print("\n=== Paper artifacts collected ===")
    print(f"Main run: {llama3_main_dir}")
    print(f"Artifacts dir: {artifacts_dir}")
    print(f"Tables written: {tables_dir}")
    print(f"Placeholder figures copied into draft: {copied}/{len(mapping)}")
    if llama3_noprotect_dir:
        print(f"Found noprotect control: {llama3_noprotect_dir}")
    if llama3_protect_baselines_dir:
        print(f"Found protect-baselines: {llama3_protect_baselines_dir}")


if __name__ == "__main__":
    main()

