#!/usr/bin/env python3
"""
Generate LaTeX tables for the SCAR ICML draft from a saved experiment results JSON.

Why:
- Avoid manual copy/paste drift between `results_*.json` and `drafts/LLM_prune/scar_paper_icml_v5.tex`.
- Make it easy to update tables after rerunning experiments.

Usage:
  python scripts/generate_scar_paper_tables.py \
    --results /abs/path/to/results_YYYYMMDD_HHMMSS.json \
    --sparsity 0.5 \
    --best-mode
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Optional, Tuple


METHODS = [
    ("Magnitude (channel)", "weight_magnitude"),
    ("Wanda (channel)", "wanda"),
    ("SparseGPT (channel)", "sparsegpt"),
    ("Act. L2", "activation_l2_norm"),
    ("RQ", "rayleigh_quotient"),
    ("SCAR-LP", "scar_loss_proxy"),
    ("SCAR-Prot", "supernode_protection_score"),
    ("SCAR-Conn", "supernode_connectivity_score"),
]


def _get_pruned_entry(
    pruning_results: Dict[str, Any],
    metric: str,
    mode: str,
    sparsity: float,
) -> Optional[Dict[str, Any]]:
    for v in pruning_results.values():
        if not isinstance(v, dict):
            continue
        if v.get("metric") == metric and v.get("mode") == mode and v.get("sparsity") == sparsity:
            return v
    return None


def _pick_mode(
    pruning_results: Dict[str, Any],
    metric: str,
    sparsity: float,
    best_mode: bool,
) -> Tuple[str, Optional[Dict[str, Any]]]:
    if not best_mode:
        entry = _get_pruned_entry(pruning_results, metric=metric, mode="low", sparsity=sparsity)
        return "low", entry

    low = _get_pruned_entry(pruning_results, metric=metric, mode="low", sparsity=sparsity)
    high = _get_pruned_entry(pruning_results, metric=metric, mode="high", sparsity=sparsity)

    def ppl(x: Optional[Dict[str, Any]]) -> float:
        if not x:
            return float("inf")
        v = x.get("perplexity")
        return float(v) if v is not None else float("inf")

    if ppl(low) <= ppl(high):
        return "low", low
    return "high", high


def _fmt(x: Any, digits: int = 1) -> str:
    if x is None:
        return "--"
    try:
        xf = float(x)
    except Exception:
        return "--"
    if xf != xf:  # NaN
        return "--"
    return f"{xf:.{digits}f}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True, type=str, help="Path to results_*.json")
    ap.add_argument("--sparsity", type=float, default=0.5, help="Target sparsity level (default: 0.5)")
    ap.add_argument(
        "--best-mode",
        action="store_true",
        help="Pick the better of low/high for each method by perplexity.",
    )
    args = ap.parse_args()

    path = Path(args.results)
    obj = json.loads(path.read_text())

    pruning_results = obj.get("pruning_results") or {}
    evaluation = obj.get("evaluation") or {}

    baseline_metrics = evaluation.get("baseline_metrics") or {}
    baseline_ppl = evaluation.get("baseline_perplexity")

    # Metrics used in the draft's Table 1
    cols = [
        ("PPL$\\downarrow$", "perplexity", 1),
        ("MMLU", "accuracy_mmlu", 1),
        ("Hella", "accuracy_hellaswag", 1),
        ("PIQA", "accuracy_piqa", 1),
        ("BoolQ", "accuracy_boolq", 1),
    ]

    print("% Auto-generated by scripts/generate_scar_paper_tables.py")
    print("\\begin{tabular}{@{}l" + "c" * len(cols) + "@{}}")
    print("\\toprule")
    print("Method & " + " & ".join(h for h, _, _ in cols) + " \\\\")
    print("\\midrule")

    # Unpruned row
    unpruned_vals = {"perplexity": baseline_ppl, **(baseline_metrics if isinstance(baseline_metrics, dict) else {})}
    print(
        "Unpruned & "
        + " & ".join(_fmt(unpruned_vals.get(k), d) for _, k, d in cols)
        + " \\\\"
    )
    print("\\midrule")

    for label, metric in METHODS:
        mode, entry = _pick_mode(pruning_results, metric=metric, sparsity=args.sparsity, best_mode=args.best_mode)
        if entry is None:
            row = [label] + ["--"] * len(cols)
            print(row[0] + " & " + " & ".join(row[1:]) + " \\\\")
            continue

        vals = {k: entry.get(k) for _, k, _ in cols}
        # Be robust: some evaluators store e.g. 'accuracy_mmlu' etc; keep '--' if missing.
        print(
            f"{label} & "
            + " & ".join(_fmt(vals.get(k), d) for _, k, d in cols)
            + f" % ({metric}, {mode})"
            + " \\\\"
        )

    print("\\bottomrule")
    print("\\end{tabular}")


if __name__ == "__main__":
    main()

